module.exports = {
    nineS: {
        dataCamouflageComplete: 'Mock data generation successful',
        scanningField: 'Scanning field differences... Bridging semantic gaps',
        dataCamouflage: fileName => `Piercing target firewall... Executing data camouflage [${fileName}]`,
    },
    pod042: {
        startScout: 'Activating [Tactical Right-Click Snapshot] mode...',
        capturedToast: 'Visual intelligence captured. Initiating transmission...',
        extractingUiMetadata: 'Extracting UI metadata from neural cloud network...',
        simulate: 'Real-fire request intercepted. Dropping simulation package: example.json',
        uploadVisualMetadata: 'Uploading visual metadata to Command for semantic analysis...',
        partialConstruction: time => `Report: Partial construction achieved. Elapsed: ${time}s`,
        capturedPage: pageName => `Page captured [${pageName}] -> Transmitted to mission directory`,
        constructionAborted: virus => `Construction aborted. Logic virus or timeout detected: ${virus}`,
        captureFailed: (name, virus) => `Warning: Optical reconnaissance failure on [${name}]: ${virus}`,
        visualPartCaptured: `Partial visual sample detected. Executing 'Fragment Construction Protocol'...`,
        noAvailablePages: `Report: No viable HTML constructs detected within ruins. Scan sequence aborted.`,
        scoutReady: '[Right-Click Snapshot Ready] Right-click anywhere on the webpage to capture instantly.',
        intercept: fileName => `Module [${fileName}] already exists. Construction skipped to prevent overwrite.`,
        relicAccessFailed: entry => `Warning: Failed to identify relic entrance at [${entry}]. Coordinates invalid.`,
        partialRecommendation: '│ Recommendation: Please manually assemble the above code block into your target file',
        partialConstructionAborted: virus => `[Warning] Fragment construction failed. Logic interference detected: ${virus}`,
        swarmScanning: entry => `Local prototype ruins detected at [${entry}]. Drone swarm reconnaissance protocol engaged.`,
        captureProgress: (curr, total, name) => `Optical survey in progress [${curr}/${total}]: Target acquired -> ${name}.png`,
        swarmVictory: count => `Strategic Report: Drone swarm survey triumphant. Airdropped ${count} blueprints into mission bay!`,
        visualCaptured: fileName => `Visual sensor captured: [${fileName}]. Allocating Bunker resources for physical construction...`,
        deployRelayServer: (count, port) => `Identified ${count} tactical blueprints. Deploying field relay terminal on port ${port}...`,
        assemblyComplete: (fileName, time) => `Protocol complete. Physical assembly of [${fileName}] achieved. Elapsed: ${time}s, Syncing Menu configuration to Bunker...`,
    },
    pod153: {
        signalLinkFault: virus => `Signal Link Fault: ${virus}`,
        alignmentFailed: virus => `Alignment failed. Encountered powerful API firewall: ${virus}`,
        signalSynchronized: (count, module) => `[${module}] Signal Synchronized: ${count} nodes energized`,
        autonomousAddressing: `Initiating 'Full-Channel Autonomous Addressing Protocol [Semantic Scan]'...`,
        inactiveModule: fileName => `Inactive module: [${fileName}]. Requesting 9S for precise alignment...`,
        reconEncryptedData: fileName => `Encrypted data source [${fileName}] detected. Initiating semantic alignment...`,
        capturedRuntimeSignal: fileName => `Captured runtime signal [${fileName}]. Executing semantic alignment protocol...`,
        unknownModule: fileName => `Module [${fileName}] resource not found in Bunker database. Please execute visual construction first`,
        bridgeProtocolComplete: (count, time) => `Semantic bridge protocol complete. Corrected ${count} field deviations. Elapsed: ${time}s`,
    },
    bunker: {
        exit: 'Signal Lost...',
        envCheck: '.env already exists',
        envCopy: '.env storage complete',
        systemStandby: 'System is STANDBY',
        configCheck: 'config.js already exists',
        configCopy: 'config.js storage complete',
        argDesc: 'Specify frontend framework template',
        desc: 'AI-powered frontend CRUD code generator',
        dataSynced: 'All data synced to Bunker storage nodes',
        initDesc: 'Initialize Bunker construction environment',
        missionUnknown: 'Unable to classify mission requirements.',
        star: 'If it saves you time, feel free to give it a ⭐ on GitHub',
        copyTemplateError: virus => `Template construction failed: ${virus}`,
        towerOnline: port => `Signal Intercept Tower Online [Band: ${port}]`,
        confirmEnemy: 'Target confirmed. Deploying the most suitable unit...',
        missionFailed: 'Mission assignment failed. No suitable unit available.',
        linkSevered: 'Link Severed: Check network status or Black Box resonance',
        systemOffline: 'Disconnecting Neural Link, Executing Physical Assembly...',
        detectedEnemy: 'Unidentified entity detected. Initiating combat analysis...',
        accessDenied: 'YoRHa Command Center Access Denied: Invalid API Key or quota exhausted!',
        bootDesc: 'Start full-channel linked monitoring: Coordinated Page/Part/API construction',
        copyEnum: `│ Backend Enums detected \n│ Weld the code below into the module's resource center`,
        towerConnected: port => `Command: Please point your local proxy target to http://localhost:${port}`,
        disclaimer: 'Match Result Reference Only. Not Final Decision. Each Unit should adjust based on battlefield conditions',
        frameworkNotSupported: template => `[${template}] framework not supported. Welcome to contribute a Pull Request to help`,
        networkInstability: count => `Neural Network instability detected. Attempting to re-establish link... (Retry #${count})`,
        strategicThreshold: (target, current) => `Physical clone count has exceeded ${target} strategic threshold! Current power: ${current}`,
        initComplete: cmd => `Bunker deployment is complete. To expedite your entry into the battlefield, I recommend a manual [Physical Assembly]: Add ${cmd} to your package.json scripts.`,
        isLegendary: (unlockAchievement, current, target) => unlockAchievement ? 'Congratulations, your construction protocol is now part of humanity' : `Current clones: ${current}. ${target - current} to Achievement`,
    },
    operator6O: {
        call2B: 'Calling 2B, all-channel linked monitoring is ready!'
    }
}