module.exports = {
    nineS: {
        dataCamouflageComplete: 'Mockデータ生成完了',
        scanningField: 'フロントエンド・バックエンド間のフィールド差分を解析中... セマンティックブリッジを起動',
        dataCamouflage: fileName => `対象ファイアウォール突破中... データ偽装プロトコルを実行 [${fileName}]`,
    },
    pod042: {
        startScout: '【右クリック即時スナップショット】モードを起動中...',
        capturedToast: '視覚データをキャプチャしました。送信を開始します...',
        partialConstruction: time => `報告：局所構築完了。処理時間: ${time}s`,
        noAvailablePages: `報告：遺跡内部に有効なHTML構造体を感知できず。作戦中断。`,
        visualPartCaptured: '局所視覚サンプルを検知。「断片構築プロトコル」を開始します',
        uploadVisualMetadata: '視覚メタデータを司令部へ送信。セマンティック解析を開始...',
        extractingUiMetadata: 'ニューラルクラウドネットワークよりUIメタデータを抽出中...',
        partialRecommendation: '│ 推奨：上記コードブロックを対象ファイルへ手動実装してください',
        partialConstructionAborted: virus => `[警告] 断片構築失敗。論理干渉を検出：${virus}`,
        captureFailed: (name, virus) => `警告：[${name}] の観測中に論理エラー発生：${virus}`,
        simulate: '実弾リクエストを検知。標準シミュレーションパッケージ example.json を投下します',
        relicAccessFailed: entry => `警告：目標遺跡 [${entry}] の侵入経路を特定できず。座標無効。`,
        constructionAborted: virus => `構築中断。論理ウイルスまたは接続タイムアウトを検出：${virus}`,
        capturedPage: pageName => `ページデータを取得【${pageName}】-> mission ディレクトリへ送信完了`,
        swarmScanning: entry => `ローカルプロトタイプ遺跡 [${entry}] を探知。ドローン群索敵プロトコル起動。`,
        scoutReady: '【スナップショット準備完了】ウェブページ上の任意の位置で【右クリック】すると即座に撮影されます。',
        deployRelayServer: (count, port) => `計${count}個の戦術ページを補足。ポート${port}にて臨時中継局を展開中...`,
        captureProgress: (curr, total, name) => `視覚マッピング進行中 [${curr}/${total}]：${name}.png を捕捉完了。`,
        visualCaptured: fileName => `視覚センサーによる捕捉完了: [${fileName}]。Bunkerリソースを展開し物理構築を開始します`,
        swarmVictory: count => `戦況報告：ドローン群による測量完了。${count}件の作戦設計図をミッションポッドへ投下。人類に栄光あれ。`,
        intercept: fileName => `モジュール [${fileName}] は既にBunkerデータベースに存在。データ上書き防止のため構築プロトコルを中断`,
        assemblyComplete: (fileName, time) => `構築プロトコル完了。モジュール [${fileName}] の実装を確認。処理時間: ${time}s, BunkerへMenuルーティング設定を同期中...`,
    },
    pod153: {
        signalLinkFault: virus => `シグナルリンク障害: ${virus}`,
        autonomousAddressing: '「全チャンネル自動アドレス指定プロトコル [セマンティック解析版]」を起動...',
        signalSynchronized: (count, module) => `[${module}] ${count}個のノード同期完了。電力供給を確認`,
        inactiveModule: fileName => `未通電モジュール [${fileName}] を検出。9Sによる高精度照合を要求します`,
        capturedRuntimeSignal: fileName => `ランタイムシグナル [${fileName}] を捕捉。自動同期プロトコルを開始`,
        alignmentFailed: virus => `シグナル同期失敗。APIデータが強力なファイアウォールに阻害されています：${virus}`,
        reconEncryptedData: fileName => `暗号化データソース [${fileName}] を検出。セマンティック同期プロトコルを試行`,
        unknownModule: fileName => `Bunkerデータベース内に [${fileName}] のリソース情報なし。先に視覚構築を実行してください`,
        bridgeProtocolComplete: (count, time) => `セマンティックブリッジ完了。${count}箇所のフィールド差異を修正。処理時間: ${time}s`,
    },
    bunker: {
        exit: 'システムシグナル消失...',
        envCopy: '.envストレージ保存完了',
        systemStandby: 'システム待機状態...',
        configCopy: 'config.jsストレージ保存完了',
        missionUnknown: 'ミッション要件を特定できません。',
        desc: 'AI駆動型フロントエンドCRUDコード生成システム',
        initDesc: '現在のディレクトリにBunker構築環境を初期化',
        argDesc: 'フロントエンドフレームワークテンプレートを指定',
        envCheck: '既存の.envファイルを検出。生成処理をスキップ',
        confirmEnemy: '目標を確認。最適戦闘ユニットを展開します...',
        detectedEnemy: '未確認対象を検知。戦術分析を開始します...',
        dataSynced: '全構築データをBunkerストレージノードへ同期完了',
        copyTemplateError: virus => `テンプレート構築失敗: ${virus}`,
        configCheck: '既存のconfig.jsファイルを検出。生成処理をスキップ',
        star: 'このシステムが役立った場合、GitHubでスターをお願いします ⭐',
        towerOnline: port => `シグナル迎撃塔オンライン [周波数: ${port}]`,
        bootDesc: '全チャンネル連携監視を開始：Page/Part/API協調構築をサポート',
        systemOffline: 'ニューラルクラウド接続を切断中。データを物理封印します...',
        accessDenied: '司令部アクセス拒否：API Keyが無効、または利用上限に達しています',
        missionFailed: 'ミッションの割り当てに失敗。適合する戦闘ユニットが見つかりません。',
        linkSevered: '接続断絶：ネットワーク状態またはブラックボックス共鳴を確認してください',
        disclaimer: '解析結果は参考情報です。最終判断は各ユニットが実環境に基づいて行ってください',
        towerConnected: port => `指令：プロキシ対象を http://localhost:${port} に設定してください`,
        networkInstability: count => `ニューラルクラウド通信不安定。再接続を試行中... (${count}回目)`,
        copyEnum: '│ バックエンド由来の遺伝子情報(Enum)を検出\n│ 推奨：以下のコード断片を対象モジュールへ実装してください',
        strategicThreshold: (target, current) => `物理複製数が戦略閾値 ${target} を突破しました。現在戦力：${current}`,
        frameworkNotSupported: template => `[${template}] フレームワークは現在未対応です。Pull Requestによる貢献を歓迎します`,
        initComplete: cmd => `Bunker展開完了。迅速な戦場投入のため、[物理実装]として ${cmd} をpackage.json scriptsへ追加してください`,
        isLegendary: (unlockAchievement, current, target) => unlockAchievement ? 'おめでとうございます、指揮官。あなたの構築プロトコルは人類の栄光の一部となりました' : `現在の構築数：${current}。${target}個の勲章獲得まで残り ${target - current} 回`,
    },
    operator6O: {
        call2B: '2Bへ通信。Bunker全チャンネル連携監視システム、起動準備完了！',
    }
}